name: evolution_console_runner
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

publish_to: none

dependencies:
  cross_cutting:
    # git: 
    #   url: git@github.com:Artem-Marakhovskyi/evolution-game.git
    #   path: cross_cutting
    path: ../cross_cutting
  evolution_heart:
    # git: 
    #   url: git@github.com:Artem-Marakhovskyi/evolution-game.git
    #   path: evolution_heart
    path: ../evolution_heart

dev_dependencies:
  lints: ^1.0.0
