name: evolution_console_runner_pseudo
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

publish_to: none

dependencies:
  evolution_console:
      # git: 
      #   url: git@github.com:Artem-Marakhovskyi/evolution-game.git
      #   path: evolution_console
      path: ../evolution_console
  cross_cutting:
    # git: 
    #   url: git@github.com:Artem-Marakhovskyi/evolution-game.git
    #   path: cross_cutting
    path: ../../cross_cutting
  evolution_engine:
    # git: 
    #   url: git@github.com:Artem-Marakhovskyi/evolution-game.git
    #   path: evolution_engine
    path: ../../evolution_engine
  yaml: 3.1.1

dev_dependencies:
  lints: ^1.0.0
