name: evolution_engine
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

publish_to: none

dependencies:
  cross_cutting:
    # git: 
    #   url: git@github.com:Artem-Marakhovskyi/evolution-game.git
    #   path: cross_cutting
    path: ../cross_cutting
  tuple: ^2.0.0
  get_it: ^7.2.0
  yaml: ^3.1.0
  json_serializable: ^6.1.4  
  json_annotation: ^4.4.0
  enum_to_string: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.7
